# -*- coding: utf-8 -*-
"""Fashion_MNIST_CNNipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lTbvSRgR6twxyhpLm8RPvrbOA0cvD-e

## 1. Extracción del dataset

En esta sección se carga el archivo comprimido que contiene el dataset Fashion-MNIST y se realiza su descompresión.

Este dataset contiene imágenes de prendas de vestir y sus respectivas etiquetas, organizadas en conjuntos de entrenamiento y prueba. La extracción permite acceder directamente a los datos para su posterior procesamiento.
"""

import os
import zipfile

zip_path = "/content/Fashion.zip"
extract_dir = "/content/fashion_data"

os.makedirs(extract_dir, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

print("Archivo extraído correctamente.")
print(os.listdir(extract_dir))

"""## 2. Verificación de archivos

Se verifica que los archivos del dataset se hayan extraído correctamente. Esto asegura que los datos necesarios para el entrenamiento estén disponibles.
"""

print(os.listdir("/content/fashion_data/Fashion"))

"""## 3. Importación de librerías

Se importan las librerías necesarias para manipulación de datos, visualización y construcción del modelo de deep learning.
"""

import gzip
import struct
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from tensorflow.keras import layers, models, optimizers

print("Librerías cargadas correctamente.")

"""## 4. Carga del dataset

Se cargan los datos desde archivos comprimidos (.gz), convirtiéndolos en arreglos NumPy para su procesamiento.
"""

def load_idx_images_gz(filepath):
    with gzip.open(filepath, 'rb') as f:
        magic, num, rows, cols = struct.unpack(">IIII", f.read(16))
        images = np.frombuffer(f.read(), dtype=np.uint8)
        images = images.reshape(num, rows, cols)
    return images

def load_idx_labels_gz(filepath):
    with gzip.open(filepath, 'rb') as f:
        magic, num = struct.unpack(">II", f.read(8))
        labels = np.frombuffer(f.read(), dtype=np.uint8)
    return labels

x_train = load_idx_images_gz("/content/fashion_data/Fashion/train-images-idx3-ubyte.gz")
y_train = load_idx_labels_gz("/content/fashion_data/Fashion/train-labels-idx1-ubyte.gz")

x_test = load_idx_images_gz("/content/fashion_data/Fashion/t10k-images-idx3-ubyte.gz")
y_test = load_idx_labels_gz("/content/fashion_data/Fashion/t10k-labels-idx1-ubyte.gz")

print(x_train.shape, x_test.shape)

"""## 5. Visualización de datos

Se muestran ejemplos del dataset para comprender las clases y verificar la correcta carga.
"""

class_names = ["T-shirt/top","Trouser","Pullover","Dress","Coat",
               "Sandal","Shirt","Sneaker","Bag","Ankle boot"]

plt.figure(figsize=(10,5))
for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(x_train[i], cmap="gray")
    plt.title(class_names[y_train[i]])
    plt.axis("off")
plt.show()

"""## 6. Preprocesamiento

Se normalizan los datos y se ajusta su forma para ser utilizados en la CNN. Además, se separa un conjunto de validación.
"""

x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

x_train = np.expand_dims(x_train, axis=-1)
x_test = np.expand_dims(x_test, axis=-1)

x_train, x_val, y_train, y_val = train_test_split(
    x_train, y_train,
    test_size=0.1,
    random_state=42,
    stratify=y_train
)

print(x_train.shape, x_val.shape)

"""## 7. Construcción del modelo CNN

En esta etapa se define la arquitectura de la red neuronal convolucional (CNN), la cual está diseñada para procesar datos de tipo imagen.

Las capas convolucionales (Conv2D) permiten extraer características espaciales relevantes, como bordes, texturas y patrones presentes en las imágenes. Estas características son fundamentales para diferenciar entre las distintas clases de prendas.

Las capas de agrupamiento (MaxPooling) reducen la dimensionalidad de las representaciones, disminuyendo la complejidad computacional y ayudando a conservar las características más importantes.

Posteriormente, la capa Flatten transforma los datos en un vector unidimensional, permitiendo su entrada a las capas densas (Dense), las cuales realizan la clasificación final.

Se incluye una capa Dropout para reducir el riesgo de sobreajuste, desactivando aleatoriamente algunas neuronas durante el entrenamiento.

Finalmente, la capa de salida utiliza la función de activación softmax, la cual permite obtener probabilidades para cada una de las clases.

El modelo se compila utilizando el optimizador Adam, que ajusta automáticamente la tasa de aprendizaje, y la función de pérdida sparse_categorical_crossentropy, adecuada para problemas de clasificación multiclase con etiquetas enteras.
"""

def build_cnn():
    model = models.Sequential([
        layers.Input(shape=(28,28,1)),
        layers.Conv2D(32,3,activation='relu'),
        layers.MaxPooling2D(),
        layers.Conv2D(64,3,activation='relu'),
        layers.MaxPooling2D(),
        layers.Flatten(),
        layers.Dense(128,activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(10,activation='softmax')
    ])

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

model = build_cnn()
model.summary()

"""## 8. Entrenamiento del modelo

En esta etapa se entrena la red neuronal convolucional utilizando el conjunto de datos de entrenamiento. Durante este proceso, el modelo ajusta sus pesos internos con el objetivo de minimizar la función de pérdida y mejorar progresivamente su capacidad de clasificación.

Se emplea un tamaño de lote (*batch size*) de 32, lo que permite un equilibrio adecuado entre eficiencia computacional y estabilidad en la actualización de los pesos. Además, el entrenamiento se realiza durante 10 épocas, de manera que el modelo pueda recorrer varias veces el conjunto de entrenamiento y aprender patrones visuales relevantes de las imágenes.

El conjunto de validación se utiliza en paralelo para monitorear el desempeño del modelo en datos no vistos durante el entrenamiento, permitiendo observar su capacidad de generalización y detectar posibles problemas de sobreajuste.
"""

history = model.fit(
    x_train, y_train,
    validation_data=(x_val, y_val),
    epochs=10,
    batch_size=32,
    verbose=1
)

"""## 9. Visualización del entrenamiento

En esta sección se analizan las métricas obtenidas durante el proceso de entrenamiento del modelo, específicamente la precisión (accuracy) y la función de pérdida (loss), tanto para el conjunto de entrenamiento como de validación.

Se espera observar un aumento progresivo en la precisión y una disminución en la pérdida, lo que indicaría que el modelo está aprendiendo correctamente. Además, la comparación entre entrenamiento y validación permite detectar posibles problemas de sobreajuste.
"""

plt.figure(figsize=(10,4))
plt.plot(history.history["accuracy"], label="Train Accuracy")
plt.plot(history.history["val_accuracy"], label="Val Accuracy")
plt.title("Accuracy durante el entrenamiento")
plt.xlabel("Épocas")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,4))
plt.plot(history.history["loss"], label="Train Loss")
plt.plot(history.history["val_loss"], label="Val Loss")
plt.title("Loss durante el entrenamiento")
plt.xlabel("Épocas")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

"""## 10. Evaluación del modelo

En esta etapa se evalúa el desempeño del modelo utilizando el conjunto de datos de prueba, el cual no fue utilizado durante el entrenamiento.

Esto permite medir la capacidad real del modelo para generalizar a nuevos datos. Se obtienen métricas como la precisión (accuracy) y la pérdida (loss), que reflejan el rendimiento global del modelo.
"""

test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)

print("Test Accuracy:", test_acc)
print("Test Loss:", test_loss)

"""## 11. Métricas de clasificación

Se calculan métricas más detalladas como precisión (precision), exhaustividad (recall) y F1-score para cada clase del problema.

Estas métricas permiten analizar el desempeño del modelo de manera más específica, identificando cómo se comporta en cada categoría. El F1-score es especialmente relevante, ya que representa un equilibrio entre precision y recall.
"""

y_pred_probs = model.predict(x_test)
y_pred = np.argmax(y_pred_probs, axis=1)

print(classification_report(y_test, y_pred, target_names=class_names))

"""## 12. Matriz de confusión

Se construye una matriz de confusión para visualizar el desempeño del modelo en cada una de las clases.

Esta herramienta permite identificar qué clases son correctamente clasificadas y cuáles presentan errores. Es especialmente útil para detectar confusiones entre categorías visualmente similares.
"""

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)

fig, ax = plt.subplots(figsize=(10,10))
disp.plot(ax=ax, xticks_rotation=45, cmap="Blues", colorbar=False)
plt.title("Matriz de confusión")
plt.show()

"""## 13. Visualización de predicciones

Se muestran ejemplos de imágenes del conjunto de prueba junto con sus etiquetas reales y las predicciones realizadas por el modelo.

Esta visualización permite evaluar de forma cualitativa el desempeño del modelo, observando directamente casos correctos e incorrectos.
"""

plt.figure(figsize=(12,8))
indices = np.random.choice(len(x_test), 12, replace=False)

for i, idx in enumerate(indices):
    plt.subplot(3,4,i+1)
    plt.imshow(x_test[idx].squeeze(), cmap="gray")
    true_label = class_names[y_test[idx]]
    pred_label = class_names[y_pred[idx]]
    plt.title(f"Real: {true_label}\nPred: {pred_label}")
    plt.axis("off")

plt.tight_layout()
plt.show()

"""## 14. Conclusiones

El modelo CNN desarrollado logró un desempeño sólido en la clasificación de imágenes del dataset Fashion-MNIST, alcanzando una precisión cercana al 92% en el conjunto de prueba.

Esto demuestra que la arquitectura utilizada es adecuada para el problema y que el modelo fue capaz de aprender patrones visuales relevantes de las imágenes. Sin embargo, se identificaron dificultades en clases con alta similitud visual, lo que representa una limitación del modelo.

Como mejoras futuras, se podrían implementar arquitecturas más profundas, técnicas de regularización adicionales y estrategias de aumento de datos (data augmentation) para mejorar aún más el rendimiento.
"""

